export const carbonProjects: Project[] = [
  {
    registry: 'verra',
    status: 'completed',
    country_code: 'BRA',
    project_type: 'reforestation',
    name: 'sample project name',
    project_id: 'VCS-BR-1021',
    score: 88,
    vintage: '2021',
    sdg: [
      { id: 13, score: 92 },
      { id: 15, score: 90 },
      { id: 8, score: 75 },
    ],
    image: '/images/projects/reforestation-brazil.jpg',
  },
  {
    registry: 'gs',
    status: 'running',
    country_code: 'IND',
    project_type: 'cookstove',
    name: 'sample project name',
    project_id: 'GS-IN-2044',
    score: 81,
    vintage: '2023',
    sdg: [
      { id: 3, score: 85 },
      { id: 7, score: 78 },
      { id: 13, score: 80 },
    ],
    image: '/images/projects/cookstove-india.jpg',
  },
  {
    registry: 'verra',
    status: 'failed',
    country_code: 'IDN',
    project_type: 'reforestation',
    name: 'sample project name',
    project_id: 'VCS-ID-1789',
    score: 42,
    vintage: '2019',
    sdg: [
      { id: 13, score: 50 },
      { id: 15, score: 45 },
    ],
    image: '/images/projects/reforestation-indonesia.jpg',
  },
  {
    registry: 'gs',
    status: 'completed',
    country_code: 'KEN',
    project_type: 'cookstove',
    name: 'sample project name',
    project_id: 'GS-KE-3312',
    score: 86,
    vintage: '2020',
    sdg: [
      { id: 1, score: 70 },
      { id: 3, score: 88 },
      { id: 5, score: 74 },
    ],
    image: '/images/projects/cookstove-kenya.jpg',
  },
  {
    registry: 'verra',
    status: 'running',
    country_code: 'VNM',
    project_type: 'renewable energy',
    name: 'sample project name',
    project_id: 'VCS-VN-4520',
    score: 79,
    vintage: '2022',
    sdg: [
      { id: 7, score: 85 },
      { id: 9, score: 72 },
      { id: 13, score: 83 },
    ],
    image: '/images/projects/solar-vietnam.jpg',
  },
  {
    registry: 'gs',
    status: 'failed',
    country_code: 'PER',
    project_type: 'waste',
    name: 'sample project name',
    project_id: 'GS-PE-1198',
    score: 48,
    vintage: '2018',
    sdg: [
      { id: 11, score: 55 },
      { id: 12, score: 50 },
      { id: 13, score: 46 },
    ],
    image: '/images/projects/waste-peru.jpg',
  },
  {
    registry: 'verra',
    status: 'completed',
    country_code: 'LKA',
    project_type: 'renewable energy',
    name: 'sample project name',
    project_id: 'VCS-LK-3901',
    score: 91,
    vintage: '2023',
    sdg: [
      { id: 7, score: 94 },
      { id: 8, score: 82 },
      { id: 13, score: 96 },
    ],
    image: '/images/projects/wind-srilanka.jpg',
  },
  {
    registry: 'gs',
    status: 'running',
    country_code: 'GHA',
    project_type: 'waste',
    name: 'sample project name',
    project_id: 'GS-GH-2677',
    score: 73,
    vintage: '2022',
    sdg: [
      { id: 11, score: 76 },
      { id: 12, score: 70 },
      { id: 13, score: 74 },
    ],
    image: '/images/projects/waste-ghana.jpg',
  },
  {
    registry: 'verra',
    status: 'completed',
    country_code: 'MEX',
    project_type: 'waste',
    name: 'sample project name',
    project_id: 'VCS-MX-5582',
    score: 84,
    vintage: '2021',
    sdg: [
      { id: 11, score: 82 },
      { id: 12, score: 79 },
      { id: 13, score: 88 },
    ],
    image: '/images/projects/waste-mexico.jpg',
  },
  {
    registry: 'gs',
    status: 'running',
    country_code: 'BGD',
    project_type: 'cookstove',
    name: 'sample project name',
    project_id: 'GS-BD-2291',
    score: 77,
    vintage: '2023',
    sdg: [
      { id: 3, score: 81 },
      { id: 5, score: 74 },
      { id: 13, score: 79 },
    ],
    image: '/images/projects/cookstove-bangladesh.jpg',
  },
  {
    registry: 'verra',
    status: 'failed',
    country_code: 'KHM',
    project_type: 'renewable energy',
    name: 'sample project name',
    project_id: 'VCS-KH-1876',
    score: 39,
    vintage: '2017',
    sdg: [
      { id: 7, score: 45 },
      { id: 9, score: 40 },
    ],
    image: '/images/projects/solar-cambodia.jpg',
  },
  {
    registry: 'gs',
    status: 'completed',
    country_code: 'MAR',
    project_type: 'renewable energy',
    name: 'sample project name',
    project_id: 'GS-MA-3419',
    score: 89,
    vintage: '2020',
    sdg: [
      { id: 7, score: 91 },
      { id: 9, score: 84 },
      { id: 13, score: 90 },
    ],
    image: '/images/projects/solar-morocco.jpg',
  },
  {
    registry: 'verra',
    status: 'running',
    country_code: 'UGA',
    project_type: 'reforestation',
    name: 'sample project name',
    project_id: 'VCS-UG-4012',
    score: 75,
    vintage: '2022',
    sdg: [
      { id: 13, score: 78 },
      { id: 15, score: 82 },
    ],
    image: '/images/projects/reforestation-uganda.jpg',
  },
  {
    registry: 'gs',
    status: 'failed',
    country_code: 'PHL',
    project_type: 'waste',
    name: 'sample project name',
    project_id: 'GS-PH-1643',
    score: 44,
    vintage: '2018',
    sdg: [
      { id: 11, score: 48 },
      { id: 12, score: 46 },
    ],
    image: '/images/projects/waste-philippines.jpg',
  },
  {
    registry: 'verra',
    status: 'completed',
    country_code: 'CHL',
    project_type: 'renewable energy',
    name: 'sample project name',
    project_id: 'VCS-CL-6120',
    score: 93,
    vintage: '2022',
    sdg: [
      { id: 7, score: 96 },
      { id: 13, score: 95 },
    ],
    image: '/images/projects/wind-chile.jpg',
  },
  {
    registry: 'gs',
    status: 'running',
    country_code: 'NPL',
    project_type: 'reforestation',
    name: 'sample project name',
    project_id: 'GS-NP-2910',
    score: 71,
    vintage: '2023',
    sdg: [
      { id: 13, score: 74 },
      { id: 15, score: 77 },
    ],
    image: '/images/projects/reforestation-nepal.jpg',
  },
  {
    registry: 'verra',
    status: 'failed',
    country_code: 'NGA',
    project_type: 'cookstove',
    name: 'sample project name',
    project_id: 'VCS-NG-1334',
    score: 36,
    vintage: '2016',
    sdg: [
      { id: 3, score: 42 },
      { id: 5, score: 38 },
    ],
    image: '/images/projects/cookstove-nigeria.jpg',
  },
  {
    registry: 'gs',
    status: 'completed',
    country_code: 'COL',
    project_type: 'reforestation',
    name: 'sample project name',
    project_id: 'GS-CO-4881',
    score: 87,
    vintage: '2021',
    sdg: [
      { id: 13, score: 90 },
      { id: 15, score: 88 },
      { id: 8, score: 76 },
    ],
    image: '/images/projects/reforestation-colombia.jpg',
  },
  {
    registry: 'verra',
    status: 'running',
    country_code: 'THA',
    project_type: 'waste',
    name: 'sample project name',
    project_id: 'VCS-TH-3098',
    score: 74,
    vintage: '2022',
    sdg: [
      { id: 11, score: 75 },
      { id: 12, score: 72 },
      { id: 13, score: 78 },
    ],
    image: '/images/projects/waste-thailand.jpg',
  },
  {
    registry: 'gs',
    status: 'failed',
    country_code: 'ETH',
    project_type: 'reforestation',
    name: 'sample project name',
    project_id: 'GS-ET-1902',
    score: 41,
    vintage: '2017',
    sdg: [
      { id: 13, score: 47 },
      { id: 15, score: 43 },
    ],
    image: '/images/projects/reforestation-ethiopia.jpg',
  },
  {
    registry: 'verra',
    status: 'completed',
    country_code: 'ESP',
    project_type: 'renewable energy',
    name: 'sample project name',
    project_id: 'VCS-ES-7721',
    score: 90,
    vintage: '2020',
    sdg: [
      { id: 7, score: 93 },
      { id: 9, score: 85 },
      { id: 13, score: 92 },
    ],
    image: '/images/projects/solar-spain.jpg',
  },
];
