// export const carbonProjects: Project[] = [
//   {
//     registry: 'verra',
//     status: 'completed',
//     country_code: 'BRA',
//     project_type: 'reforestation',
//     name: 'sample project name',
//     project_id: 'VCS-BR-1021',
//     score: 88,
//     vintage: '2021',
//     sdg: [
//       { id: 13, score: 92 },
//       { id: 15, score: 90 },
//       { id: 8, score: 75 },
//     ],
//     image: '/images/projects/reforestation-brazil.jpg',
//   },
//   {
//     registry: 'gs',
//     status: 'running',
//     country_code: 'IND',
//     project_type: 'cookstove',
//     name: 'sample project name',
//     project_id: 'GS-IN-2044',
//     score: 81,
//     vintage: '2023',
//     sdg: [
//       { id: 3, score: 85 },
//       { id: 7, score: 78 },
//       { id: 13, score: 80 },
//     ],
//     image: '/images/projects/cookstove-india.jpg',
//   },
//   {
//     registry: 'verra',
//     status: 'failed',
//     country_code: 'IDN',
//     project_type: 'reforestation',
//     name: 'sample project name',
//     project_id: 'VCS-ID-1789',
//     score: 42,
//     vintage: '2019',
//     sdg: [
//       { id: 13, score: 50 },
//       { id: 15, score: 45 },
//     ],
//     image: '/images/projects/reforestation-indonesia.jpg',
//   },
//   {
//     registry: 'gs',
//     status: 'completed',
//     country_code: 'KEN',
//     project_type: 'cookstove',
//     name: 'sample project name',
//     project_id: 'GS-KE-3312',
//     score: 86,
//     vintage: '2020',
//     sdg: [
//       { id: 1, score: 70 },
//       { id: 3, score: 88 },
//       { id: 5, score: 74 },
//     ],
//     image: '/images/projects/cookstove-kenya.jpg',
//   },
//   {
//     registry: 'verra',
//     status: 'running',
//     country_code: 'VNM',
//     project_type: 'renewable energy',
//     name: 'sample project name',
//     project_id: 'VCS-VN-4520',
//     score: 79,
//     vintage: '2022',
//     sdg: [
//       { id: 7, score: 85 },
//       { id: 9, score: 72 },
//       { id: 13, score: 83 },
//     ],
//     image: '/images/projects/solar-vietnam.jpg',
//   },
//   {
//     registry: 'gs',
//     status: 'failed',
//     country_code: 'PER',
//     project_type: 'waste',
//     name: 'sample project name',
//     project_id: 'GS-PE-1198',
//     score: 48,
//     vintage: '2018',
//     sdg: [
//       { id: 11, score: 55 },
//       { id: 12, score: 50 },
//       { id: 13, score: 46 },
//     ],
//     image: '/images/projects/waste-peru.jpg',
//   },
//   {
//     registry: 'verra',
//     status: 'completed',
//     country_code: 'LKA',
//     project_type: 'renewable energy',
//     name: 'sample project name',
//     project_id: 'VCS-LK-3901',
//     score: 91,
//     vintage: '2023',
//     sdg: [
//       { id: 7, score: 94 },
//       { id: 8, score: 82 },
//       { id: 13, score: 96 },
//     ],
//     image: '/images/projects/wind-srilanka.jpg',
//   },
//   {
//     registry: 'gs',
//     status: 'running',
//     country_code: 'GHA',
//     project_type: 'waste',
//     name: 'sample project name',
//     project_id: 'GS-GH-2677',
//     score: 73,
//     vintage: '2022',
//     sdg: [
//       { id: 11, score: 76 },
//       { id: 12, score: 70 },
//       { id: 13, score: 74 },
//     ],
//     image: '/images/projects/waste-ghana.jpg',
//   },
//   {
//     registry: 'verra',
//     status: 'completed',
//     country_code: 'MEX',
//     project_type: 'waste',
//     name: 'sample project name',
//     project_id: 'VCS-MX-5582',
//     score: 84,
//     vintage: '2021',
//     sdg: [
//       { id: 11, score: 82 },
//       { id: 12, score: 79 },
//       { id: 13, score: 88 },
//     ],
//     image: '/images/projects/waste-mexico.jpg',
//   },
//   {
//     registry: 'gs',
//     status: 'running',
//     country_code: 'BGD',
//     project_type: 'cookstove',
//     name: 'sample project name',
//     project_id: 'GS-BD-2291',
//     score: 77,
//     vintage: '2023',
//     sdg: [
//       { id: 3, score: 81 },
//       { id: 5, score: 74 },
//       { id: 13, score: 79 },
//     ],
//     image: '/images/projects/cookstove-bangladesh.jpg',
//   },
//   {
//     registry: 'verra',
//     status: 'failed',
//     country_code: 'KHM',
//     project_type: 'renewable energy',
//     name: 'sample project name',
//     project_id: 'VCS-KH-1876',
//     score: 39,
//     vintage: '2017',
//     sdg: [
//       { id: 7, score: 45 },
//       { id: 9, score: 40 },
//     ],
//     image: '/images/projects/solar-cambodia.jpg',
//   },
//   {
//     registry: 'gs',
//     status: 'completed',
//     country_code: 'MAR',
//     project_type: 'renewable energy',
//     name: 'sample project name',
//     project_id: 'GS-MA-3419',
//     score: 89,
//     vintage: '2020',
//     sdg: [
//       { id: 7, score: 91 },
//       { id: 9, score: 84 },
//       { id: 13, score: 90 },
//     ],
//     image: '/images/projects/solar-morocco.jpg',
//   },
//   {
//     registry: 'verra',
//     status: 'running',
//     country_code: 'UGA',
//     project_type: 'reforestation',
//     name: 'sample project name',
//     project_id: 'VCS-UG-4012',
//     score: 75,
//     vintage: '2022',
//     sdg: [
//       { id: 13, score: 78 },
//       { id: 15, score: 82 },
//     ],
//     image: '/images/projects/reforestation-uganda.jpg',
//   },
//   {
//     registry: 'gs',
//     status: 'failed',
//     country_code: 'PHL',
//     project_type: 'waste',
//     name: 'sample project name',
//     project_id: 'GS-PH-1643',
//     score: 44,
//     vintage: '2018',
//     sdg: [
//       { id: 11, score: 48 },
//       { id: 12, score: 46 },
//     ],
//     image: '/images/projects/waste-philippines.jpg',
//   },
//   {
//     registry: 'verra',
//     status: 'completed',
//     country_code: 'CHL',
//     project_type: 'renewable energy',
//     name: 'sample project name',
//     project_id: 'VCS-CL-6120',
//     score: 93,
//     vintage: '2022',
//     sdg: [
//       { id: 7, score: 96 },
//       { id: 13, score: 95 },
//     ],
//     image: '/images/projects/wind-chile.jpg',
//   },
//   {
//     registry: 'gs',
//     status: 'running',
//     country_code: 'NPL',
//     project_type: 'reforestation',
//     name: 'sample project name',
//     project_id: 'GS-NP-2910',
//     score: 71,
//     vintage: '2023',
//     sdg: [
//       { id: 13, score: 74 },
//       { id: 15, score: 77 },
//     ],
//     image: '/images/projects/reforestation-nepal.jpg',
//   },
//   {
//     registry: 'verra',
//     status: 'failed',
//     country_code: 'NGA',
//     project_type: 'cookstove',
//     name: 'sample project name',
//     project_id: 'VCS-NG-1334',
//     score: 36,
//     vintage: '2016',
//     sdg: [
//       { id: 3, score: 42 },
//       { id: 5, score: 38 },
//     ],
//     image: '/images/projects/cookstove-nigeria.jpg',
//   },
//   {
//     registry: 'gs',
//     status: 'completed',
//     country_code: 'COL',
//     project_type: 'reforestation',
//     name: 'sample project name',
//     project_id: 'GS-CO-4881',
//     score: 87,
//     vintage: '2021',
//     sdg: [
//       { id: 13, score: 90 },
//       { id: 15, score: 88 },
//       { id: 8, score: 76 },
//     ],
//     image: '/images/projects/reforestation-colombia.jpg',
//   },
//   {
//     registry: 'verra',
//     status: 'running',
//     country_code: 'THA',
//     project_type: 'waste',
//     name: 'sample project name',
//     project_id: 'VCS-TH-3098',
//     score: 74,
//     vintage: '2022',
//     sdg: [
//       { id: 11, score: 75 },
//       { id: 12, score: 72 },
//       { id: 13, score: 78 },
//     ],
//     image: '/images/projects/waste-thailand.jpg',
//   },
//   {
//     registry: 'gs',
//     status: 'failed',
//     country_code: 'ETH',
//     project_type: 'reforestation',
//     name: 'sample project name',
//     project_id: 'GS-ET-1902',
//     score: 41,
//     vintage: '2017',
//     sdg: [
//       { id: 13, score: 47 },
//       { id: 15, score: 43 },
//     ],
//     image: '/images/projects/reforestation-ethiopia.jpg',
//   },
//   {
//     registry: 'verra',
//     status: 'completed',
//     country_code: 'ESP',
//     project_type: 'renewable energy',
//     name: 'sample project name',
//     project_id: 'VCS-ES-7721',
//     score: 90,
//     vintage: '2020',
//     sdg: [
//       { id: 7, score: 93 },
//       { id: 9, score: 85 },
//       { id: 13, score: 92 },
//     ],
//     image: '/images/projects/solar-spain.jpg',
//   },
// ];

export const projects = [
  {
    VCS_689: {
      resourceIdentifier: "689",
      resourceName: "Reforestation of degraded land in Chhattisgarh, India",
      description:
        "The land to be reforested under the project activity has been a degraded land and would have continued to degrade in the absence of the project activity. The natural land conditions did not permit arrival and establishment of forest propagules. The project area is a revenue area, obtained from the villagers and secluded from the forest lands. The lands under project activity are locally known as Bhata Lands that have poor water holding capacity; no vegetation and are heavily prone to wind and water erosion. Thus, the major purposes of the project activity are to: 1. Enhance carbon sink through reforestation. 2. Reclaim the degraded land in a sustainable manner 3. Reduce pressure on natural forests of the region 4. Uplift socio-economic status of native rural",
      location: {
        latitude: 21.543921,
        longitude: 81.25426,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "5007",
      total_buffer_pool_credits: 4402,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "282 Hectares",
      ccb_project_status: "Validation expired",
      sdvista_project_status: null,
    },
    VCS_1175: {
      resourceIdentifier: "1175",
      resourceName:
        "AVOIDING PLANNED DEFORESTATION AND DEGRADATION IN THE VALDIVIAN COASTAL RESERVE, CHILE",
      description:
        "The Valdivian Coastal Reserve is part of an ancient temperate rainforest rising from Chile’s southern coastline. Owned and managed by The Nature Conservancy since 2003, the 50,251 hectare (124,173 acre) Reserve is home to biological treasures such as Olivillo trees, living up to 400 years, Alerce trees, with a lifespan of more than 3,000 years, and one of the world’s smallest deer called the pudú. By purchasing the Reserve in 2003, the Conservancy was able to stop an immediate threat of deforestation associated with the construction of a coastal highway through the property, and to stop the ongoing conversion of native forest to exotic plantations, by cancelling the legal and transferrable forest management permits which had allowed forest conversion. With these actions taken to stop deforestation and degradation of native forests, more than 350,000 tons of CO2 emissions are estimated to have been prevented from being released into the atmosphere—the equivalent of taking more than 67,000 passenger vehicles off U.S. roads for one full year. The Conservancy has been working closely with neighboring fishing villages and indigenous communities to maintain traditional land uses and to encourage compatible local economic development as part of the Valdivian Coastal Reserve’s overall conservation strategy. The Conservancy works with partners to make the Reserve both accessible and educational to all visitors, driving tourism that is crucial for the economic sustainability of local communities. Tourists represent a market for sustainably produced goods, such as locally gathered organic honey and herbal teas. Thus, the project not only helps fight climate change and protects biodiversity, but it also supports sustainable economic activities for local people.",
      location: {
        latitude: -40.202382,
        longitude: -73.709187,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "58154",
      total_buffer_pool_credits: 32434,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "50251 Hectares",
      ccb_project_status: "Verification expired",
      sdvista_project_status: null,
    },
    VCS_1566: {
      resourceIdentifier: "1566",
      resourceName:
        "REDD+ Project Resguardo Indigena Unificado Selva de Mataven (RIU SM)",
      description:
        "REDD+ Project Resguardo Indígena Unificado–Selva de Mataven (REDD+ RIU-SM) aims to develop a participatory process to achieve the establishment of an integrated management system of forests and lands of the reserve, to ensure its sustainability and to mitigate threats of its conservation, particularly avoiding deforestation through the implementation of a REDD+ Project (Reducing Emissions from Deforestation and Forest Degradation + conserving carbon stocks, sustainable management of forests and enhancement of forest reserves in developing countries) that allows providing compensation payments for ecosystem services. The technology corresponds to a REDD Project in accordance with standards established by the VCS. Specifically an activity “Avoiding Unplanned Deforestation and Degradation (AUDD)”. The Indigenous Reservation is located east of the high plain Orinoco Colombian region in the transition belt between the savannas of the Orinoco and the Amazon forests, in Department of Vichada",
      location: {
        latitude: 4.244444,
        longitude: -68.393333,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "3622352",
      total_buffer_pool_credits: 2845250,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "1150212 Hectares",
      ccb_project_status: "Verification approval requested ",
      sdvista_project_status: "Undergoing validation and verification",
    },
    VCS_2249: {
      resourceIdentifier: "2249",
      resourceName: "HENAN FANGCHENG AND TANGHE AFFORESTATION PROJECT",
      description:
        "All sites were barren hills at least 10 years prior to the implementation of the project, the project will not convert native ecosystems to create GHG emission reductions or removals.The project is to establish forest on the barren hills to generate GHG emission reductions or removals and contribute to local sustainable development. The project is implemented by about 32,722.7 ha of forest is to be established by direct planting on barren hills in Fangcheng county and Tanghe county, Nanyang City, Henan Province.",
      location: {
        latitude: 33.066665,
        longitude: 112.633322,
      },
      vcs_project_status: "On Hold - see notification letter",
      estimated_annual_emission_reduction: "450033",
      total_buffer_pool_credits: 25623,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "26911 Hectares",
      ccb_project_status: "On Hold - see notification letter",
      sdvista_project_status: null,
    },
    VCS_856: {
      resourceIdentifier: "856",
      resourceName: "The Chocó-Darién Conservation Corridor REDD Project",
      description:
        "The Chocó-Darién Conservation Corridor is the first REDD+ project to be issued credits for activities co-designed and implemented on a community-owned, collective land title. The project protects 13,465 hectares of tropical rainforest in the Darién region of northwest Colombia, one of the most biologically diverse regions on the planet. Developed by Anthrotect, the project is co-designed and managed with COCOMASUR, an Afro-Colombian community association in the municipality of Acandí that received collective title to the project area in 2005. Cattle ranching is very common in Acandí, and there are an estimated 47,000 heads of cattle in the vicinity of the project. Working together, COCOMASUR and Anthrotect have designed a strategy to stop the spread of ranching into the project area, thereby protecting Afro-Colombian livelihoods as well as the forests on which they depend.",
      location: {
        latitude: 8.468405,
        longitude: -77.341723,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "80938",
      total_buffer_pool_credits: 82913,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "13465 Hectares",
      ccb_project_status: "Verification approved",
      sdvista_project_status: null,
    },
    VCS_634: {
      resourceIdentifier: "634",
      resourceName: "Bos Dairy Farm Project",
      description:
        "Reduction of methane production from anaerobic manure management system through removal of solids from manure slurry stream. This GHG emission reductions project was contracted in regard to its validation/verification under ISO 14064-2 and the VCS 2007 standard as another project activities type of project (TYPE III).",
      location: {
        latitude: 36.163831,
        longitude: -119.23286,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "8200",
      total_buffer_pool_credits: null,
      primary_project_category:
        "Livestock, enteric fermentation, and manure management",
      subcategory: null,
      project_acreage: null,
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_605: {
      resourceIdentifier: "605",
      resourceName:
        "Protection of a Tasmanian native forest - Project 1 - REDD Forests Pilot",
      description:
        "This project is on the private land of a family who have owned and logged the land for over one hundred years. The site is therefore under threat of continued selective logging with natural regeneration, a land management policy implemented recently across a significant swathe of the property. The owners are seeking an alternative which will provide them with a comparable income, while protecting and improving the native forests of the region. This will support local biodiversity conservation, maintain watersheds and enhance carbon stocks.",
      location: {
        latitude: -41.823371,
        longitude: 146.971048,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "4956",
      total_buffer_pool_credits: 1932,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "48630 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_2609: {
      resourceIdentifier: "2609",
      resourceName: "KUAMUT RAINFOREST CONSERVATION PROJECT",
      description:
        "The Kuamut Rainforest Conservation Project (‘Kuamut Project’) aims to protect and restore 83,381 ha of tropical forest in Sabah, Malaysia. The project is located in the Tongod and Kinabatangan Districts of Sabah, Malaysia. The project area is part of a long-term approximately 1-million-hectare concession granted to Yayasan Sabah on a 99-year lease arrangement with the Sabah Forestry Department (acting on behalf of the State Government of Sabah). Yayasan Sabah is a State-owned para-governmental charitable foundation that was formed in 1966 with the aim of ‘improving the lives of Malaysians living in Sabah’. \r\nPrior to the start of the project, the project area was designated as production forest (Class II). The area had been repeatedly logged in the past and was designated for further commercial exploitation. Project additionality is explicitly demonstrated by preventing 84,000 hectares of commercial logging over 30 years. Had the project not intervened, the resulting carbon emissions over this period would have contributed 16 million tonnes of carbon dioxide equivalent (tCO2e) into the atmosphere. \r\nIn addition to its contribution to preventing the release of greenhouse gas (GHG) emissions, the project is protecting an important biodiverse habitat, Despite its ex-logged state, the area is known to support very high populations of elephants, banteng and orangutan, and endangered bird species including Helmeted Hornbill, Bornean Peacock Pheasant and Storms Stork.",
      location: {
        latitude: 5.2,
        longitude: 117.333331,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "543049",
      total_buffer_pool_credits: 844077,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "IFM",
      project_acreage: "83381 Hectares",
      ccb_project_status: "Verification approved",
      sdvista_project_status: null,
    },
    VCS_1202: {
      resourceIdentifier: "1202",
      resourceName: "LOWER ZAMBEZI REDD+ PROJECT",
      description:
        "The Lower Zambezi REDD+ Project is a reducing emission from deforestation and degradation (REDD+) project on 38,781 ha (ha) of privately-owned land in Rufunsa District, Zambia.  The Project Area is known as ‘Rufunsa Conservancy’ (Conservancy),and is one of the last intact areas of forest within Lusaka Province (named after the nearby capital city), and provides a 60-kilometer buffer to Lower Zambezi National Park (NP), a strategic protected area in Zambia in a globally significant trans-frontier conservation area. Lower Zambezi NP is adjacent to Mana Pools National Park in Zimbabwe which is a UNESCO designated World Heritage Site. The population of the Project Zone is approximately 8,300 people living in 28 villages spread within 4 community zones.  The Project Proponent is BioCarbon Partners.",
      location: {
        latitude: -15.494631,
        longitude: 29.296648,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "189117",
      total_buffer_pool_credits: 282811,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "40126 Hectares",
      ccb_project_status: "Verification approved",
      sdvista_project_status: null,
    },
    VCS_1825: {
      resourceIdentifier: "1825",
      resourceName: "Afforestation Project in Xining City",
      description:
        "Afforestation Project in Xining City (hereinafter referred to as “the project”) is located in the suburbs of Chengdong District, Chengbei District, Chengzhong District, and Datong County, Xining City, Qinghai Province of China, whose aim is to increase carbon sequestration andcontribute to local sustainable development by planting trees on the barren or degraded lands.The project is implemented by Qinghai Forestry Ecological Construction and Investment Co., Ltd. 12,874.08ha (193,111.20Mu) of forest is to be planted by direct planting on degraded lands in Xining City, including three suburbs and one county: Chengdong District, Chengbei District, Chengzhong District, and Datong County. All the project sites were previously degraded grassland and barren land. There is no natural renewal and reforestation before the project. The implementation of the project would generate GHG emission removals and improve local environment through growing of the trees, increase income of local residents by offering job opportunities from the project, enhance the capabilities of local communities and residents by providing their relevant technical skills and training, and increase local biodiversity as a result of establishing a forest of native trees (Picea crassifolia, Sabina przewalskii, Pinus tabulaeformis, Populus, Betula).The project is estimated to generate GHG emission removals of 49,998,229tCO2e in 100 years, with an average annual GHG emission removal of 499,982 tCO2e.",
      location: {
        latitude: 37.138395,
        longitude: 101.271653,
      },
      vcs_project_status: "On Hold - see notification letter",
      estimated_annual_emission_reduction: "499982",
      total_buffer_pool_credits: 9311,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "12874 Hectares",
      ccb_project_status: "On Hold - see notification letter",
      sdvista_project_status: null,
    },
    VCS_1882: {
      resourceIdentifier: "1882",
      resourceName:
        "REDD+ PROJECT IN THE ALTO HUAYABAMBA CONSERVATION CONCESSION (CCAH)",
      description:
        "The REDD+ project in the Alto Huayabamba Concession Conservation (CCAH) is located in the region of San Martín in the central north of Peru. The CCAH covers an area of 143,928.09 ha at an altitude between 1800-4670 meters above sea level, with two well-defined ecosystems: a) the so-called Paramos of the central cordillera; and b) the so-called Peruvian Yungas or mountain forests. The area of the project is in the forest-covered zone of the CCAH and covers 53,410 ha, located in the Corridor of Conservation Abiseo-Cóndor-Kutukú, in the two countries of Ecuador and Peru; within the hotspot of the eastern mountains of the Tropical Andes and the Great Forest Area of the Amazon in the lower Andean-Amazonian areas.\r\n\r\nWithin the area of the project exists a total of 40 families, widespread and in two (2) settlements: Nuevo Bolívar and El Progreso, with 26 families in the latter two, who make use of and are dependent of the forest.\r\n\r\nThe area of the project has an exceptional value of the biodiversity, where 310 species amongst the amphibians, reptiles, birds, and mammals have been identified as objects of the conservation for the Peruvian Yungas (highest number of occurrence per area for the Peruvian Yungas for 52 species), the yellow-tailed woolly monkey (Oreonax flavicauda) being the flag species of the CCAH.\r\n\r\nThe general objective of the project is the conservation of the CCAH's montane forests to protect their exceptional biodiversity and the ecosystem services they provide, without undermining the opportunities to improve the living conditions of the population that depend on these forests. The conservation of the CCAH's forests will prevent the emission of 52,425 tCO2e per year.",
      location: {
        latitude: -7.591101,
        longitude: -77.412497,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "53179",
      total_buffer_pool_credits: 53981,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "53410 Hectares",
      ccb_project_status: "Verification approval requested ",
      sdvista_project_status: null,
    },
    VCS_934: {
      resourceIdentifier: "934",
      resourceName: "The Mai Ndombe REDD+ Project",
      description:
        "The Mai Ndombe REDD+ Project, located in western DRC, Africa, will protect 248,956 hectares of forest from industrial logging, unsustainable fuel wood extraction and slash and burn agriculture. Carbon validation will be undertaken by the Verified Carbon Standard (VCS) and major socio-economic co-benefits ensured by the Climate, Community and Biodiversity (CCB) standard. The project is developed and managed in a joint venture by forest carbon leaders ERA-Ecosystem Restoration Associates Inc. and Wildlife Works Carbon LLC. This groundbreaking project will be the first of its kind in the Congo Basin and utilizes the novel methodology developed by Wildlife Works, VM0009, 'Methodology for Avoided Deforestation' approved by the VCS in October, 2012. The project is estimated to deliver over 175MT CO2-e over 30 years.",
      location: {
        latitude: -1.957187,
        longitude: 18.043932,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "5671613",
      total_buffer_pool_credits: 4309734,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "299640 Hectares",
      ccb_project_status: "Verification approved",
      sdvista_project_status: null,
    },
    VCS_904: {
      resourceIdentifier: "904",
      resourceName:
        "Reduced Emissions from Deforestation and Degradation in Community Forests – Oddar Meanchey, Cambodia",
      description:
        "Verification to the CCB Standards Second Edition, Climate, Community & Biodiversity Gold Levels, achieved on 28 August 2013; expired 27 August 2018.The Oddar Meanchey project is Cambodia’s first REDD project, supporting 13 Community Forestry Groups in reducing deforestation through the implementation of project activities designed to address key drivers of deforestation and improve livelihoods across nearly 65,000 hectares. The project is being implemented by the Forestry Administration of Cambodia, Pact, Terra Global Capital and the Children's Development Association, with funding support provided by the Clinton Foundation, United Nations Development Programme, Terra Global Capital and Pact, and pro-bono legal counsel provided by SNR Denton.",
      location: {
        latitude: 14.267419,
        longitude: 103.786252,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "204792",
      total_buffer_pool_credits: 5969,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "63831 Hectares",
      ccb_project_status: "Verification expired",
      sdvista_project_status: null,
    },
    VCS_647: {
      resourceIdentifier: "647",
      resourceName: "Boden Creek Ecological Preserve Forest Carbon Project",
      description:
        "This REDD+ project is located on The Boden Creek Ecological Preserve (5213 ha), a private reserve located in southern Belize. The property was purchased in 1998 because of its strategic position as a critical biological corridor link between the terrestrial and the marine environments and because of its conservation importance.  It is validated and verified under VCS. The core objective of this project is to commercialize the forest carbon offsets at the Boden Creek Ecological Preserve near Punta Gorda, Belize, Central America.  This property has been the site of a groundbreaking effort to use ecotourism as a funding source for land preservation.  Due to the global economic downturn it is imperative that additional funding sources be secured to stabilize the operation.  This land is currently under immediate threat of land conversion for agriculture, and it contains documented populations of internationally protected biodiversity.",
      location: {
        latitude: 16.309633,
        longitude: -88.793452,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "57718",
      total_buffer_pool_credits: 29951,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "3980 Hectares",
      ccb_project_status: "Validation expired",
      sdvista_project_status: null,
    },
    VCS_2723: {
      resourceIdentifier: "2723",
      resourceName: "CONDOTO REDD+",
      description:
        "The CONDOTO REDD+ Project seeks the conservation of forests located in the territories of the afro communities organized as the Major Community Council of Condoto and Iró, located within the municipalities of Condoto and Río Iró, in the department of Chocó. The project zone has a total area of 65.026 ha, out of which 46.191 ha were forest in 2015. The area is characterized for its high biodiversity and rain tropical forests, but also for the presence of deforestation activities and social conflicts. Deforestation drivers include mining activities, subsistence agriculture, and activities of illegal use. Social issues include absence of the state and lack of sanitation, education and health infrastructure and lack of technical guidance regarding sustainable production models.\r\n\r\nThe project aims to mitigate the effects caused by climate change by reducing CO2 emissions derived from deforestation and forest degradation, restore degraded forest lands, promote sustainable management of forests and develop productive activities to improve community welfare. The project also seeks to protect biodiversity and high conservation values, enhance ecological connectivity and secure natural habitats of vulnerable species (including those within some category of threat and those that represent ecological interest.",
      location: {
        latitude: 5.089546,
        longitude: -76.652079,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "249943",
      total_buffer_pool_credits: 44132,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "65452 Hectares",
      ccb_project_status: "Verification approval requested ",
      sdvista_project_status: null,
    },
    VCS_1378: {
      resourceIdentifier: "1378",
      resourceName:
        "Forestry Project for the Basin of the Chinchina River, an Environmental and Productive Alternative for the City and the Region",
      description:
        "The primary objective of this project is to regulate and improve the quantity and quality of fresh water for the region’s communities by restoring the watersheds that supply their water systems, each duly identified as part of the Chinchiná River watershed restoration program. The program’s activities involve ecological restoration through assisted natural regeneration and reforestation. The species used for the assisted natural regeneration system come from the natural forests within the project boundary",
      location: {
        latitude: 4.5613,
        longitude: -75.21,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "12189",
      total_buffer_pool_credits: 28499,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "4539 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_2535: {
      resourceIdentifier: "2535",
      resourceName: "Skyridge Farms Advanced Solid Separation Project",
      description:
        "This project utilizes LWR's First Wave system to separate solids from animal waste at Skyridge Farms in Sunnyside, WA.",
      location: {
        latitude: 46.39864,
        longitude: -120.019942,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "10000",
      total_buffer_pool_credits: null,
      primary_project_category:
        "Livestock, enteric fermentation, and manure management",
      subcategory: null,
      project_acreage: null,
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_658: {
      resourceIdentifier: "658",
      resourceName:
        "Reforestation of pastures in Campo Verde with native species, Pucallpa, Peru",
      description:
        "Widely viewed as a best-practice model for tropical forestry and sustainable development, this award-winning project has seen 919.3 hectares of degraded pasture land reforested with valuable native trees through direct planting and promotion of natural regeneration in the department of Ucayali in the Amazon region of Peru.",
      location: {
        latitude: -8.581915,
        longitude: -74.741264,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "5600",
      total_buffer_pool_credits: 2998,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "920 Hectares",
      ccb_project_status: "Validation expired",
      sdvista_project_status: null,
    },
    VCS_1360: {
      resourceIdentifier: "1360",
      resourceName:
        "Forest Management to reduce deforestation and degradation in Shipibo Conibo and Cacataibo Indigenous communities of Ucayali region",
      description:
        "The Ucayali Region is located in the central part of eastern Peru, with an approximate area of 105 082.69 km2, is the second region, after the Loreto Region, to introduce greater extent. Politically bounded on the north by the Loreto Region; on the south by the Regions of Junín, Cusco and Madre de Dios; on the west by the Huánuco and Pasco regions; on the east by the State of Acre - Brazil. It is divided into 4 provinces: Padre Abad, Coronel Portillo and Atalaya Purus; for a total of 15 districts . It has 432,000 inhabitants, according to the National Census of 2007. In Ucayali live 14 ethnic families with a population of 40 thousand people, representing 12 percent of total amazonian indigenous population.The project is developed in 07 native communities belonging to ethnic and Cacataibo Shibipo Conibo, which grouped occupy an area of 127,004.0 hectares. The purpose of the project is to conserve the forests of these communities with the advance of deforestation and degradation.",
      location: {
        latitude: -9.20195,
        longitude: -74.387325,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "564818",
      total_buffer_pool_credits: 350813,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "119468 Hectares",
      ccb_project_status: "Verification approval requested ",
      sdvista_project_status: null,
    },
    VCS_514: {
      resourceIdentifier: "514",
      resourceName:
        "Promoting Sustainable Development through Natural Rubber Tree Plantations in Guatemala",
      description:
        "Validation achieved to the CCB Standards Second Edition, Biodiversity Gold Level, on 27 February 2014. Gap validation to remove two farms from the project area and verification achieved to the CCB Standards Second Edition, Biodiversity Gold Level on 03 March 2017.  The project will establish rubber tree plantations in a project boundary of 2,366.16 hectares of degraded and degrading lands where the traditional use has been cattle grazing, which corresponds to eligible area. The species planted will be Hevea brasiliensis. Direct planting of H. brasiliensis in the project area began in 2007 and will continue through 2013. The real or effective planted area corresponds to 2,252.23 hectares which is given by planting density of natural rubber plantations.  This area excludes other vegetated areas within project boundary such as creeks, borders’ vegetation, and small spots of vegetation.",
      location: {
        latitude: 14.458248,
        longitude: -91.294307,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "46434",
      total_buffer_pool_credits: 49754,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "1433 Hectares",
      ccb_project_status: "Verification approved",
      sdvista_project_status: null,
    },
    VCS_818: {
      resourceIdentifier: "818",
      resourceName: "Protection of the Bolivian Amazon Forest",
      description:
        "Validation achieved to the CCB Standards Second Edition, Biodiversity Gold Level, on 26 March 2012; expired on 26 March 2017.This project will protect the Bolivian Amazon forest from planned deforestation, initially protecting 235 has of tropical rain forest. The methodology implemented is:·VM0007 REDD Methodology Framework but limited to the planned deforestation activities Protection of the project areas under this methodology will prevent the emissions from deforestation and conversion to pastures and allow the forest to reclaim its status as a primary forest.The project is a grouped project and the instances must be located in the only geographic area defined by the union of the Departments of Pando or Beni in Bolivia.  The instances must be under threat of planned deforestation for conversion to agricultural activities as defined under VM0007 at the time the project proponent took ownership of the project area.",
      location: {
        latitude: -12.147935,
        longitude: -66.286896,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "5885",
      total_buffer_pool_credits: 6925,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "235 Hectares",
      ccb_project_status: "Validation expired",
      sdvista_project_status: null,
    },
    VCS_1133: {
      resourceIdentifier: "1133",
      resourceName: "Yacumama Forest Carbon Project",
      description:
        "The overall goal for the Yacumama Forest Carbon Project (“Project”) is to protect and conserve the tropical lowland floodplain forest on Yacumama, a privately held lodge, research, education, and conservation area, in the Amazon Basin of Peru, for long-term carbon sequestration. In addition, the Project also serves to protect, maintain, and (for some taxa) improve native biodiversity while supporting local community livelihoods by increasing sustainable economic opportunities. The climate objective for the Project is to avoid emissions from deforestation and degradation. The entire property including the Project Area will, by economic necessity, be sold by the owners in the absence of funding from carbon financing. Because the owners have legal permission to harvest the entire property, which under Peruvian law transfers with the sale, the most likely buyer would be a company who would harvest the entire property, sell the valuable wood, burn the remaining woody biomass, and implement agricultural conversion on the fertile floodplain soils.",
      location: {
        latitude: -4.60025,
        longitude: -73.409591,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "51013",
      total_buffer_pool_credits: 44646,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "2387 Hectares",
      ccb_project_status: "Project withdrawn",
      sdvista_project_status: null,
    },
    VCS_1071: {
      resourceIdentifier: "1071",
      resourceName: "Jatropha Agroforestry Senegal",
      description:
        "The Jatropha Agroforestry Senegal project developes Jatropha curcas plantations in the Fatick, Kaffrine and Kaolack regions, in central-western agricultural region of the Senegal. The Jatropha curcas plantations will cover a total area of 1411 hectares by the year 2020. The project proponent, African National Oil Corporation s.a.r.l. (ANOC), is developing the project in collaboration with CarbonSinkGroup s.r.l (www.carbonsink.it) and Agroils Technologies SpA (www.agroils.com).",
      location: {
        latitude: 13.991189,
        longitude: -16.466134,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "1742",
      total_buffer_pool_credits: 141,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "1411 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_2319: {
      resourceIdentifier: "2319",
      resourceName: "Agroforestry plantation Bateke Plateau, Republic of Congo",
      description:
        "This savannah Land Afforestation Project on the Batéké Plateaus north of Brazzaville aims to develop an alternative and renewable source of wood for urban use, based on the establishment of forest plantations adapted to these needs. These plantations will be set up in anthropogenic savannahs, i.e. land with a biomass stock blocked at a very low stage due to recurrent bushfires. The savannahs are deliberately fired at frequent intervals (at least once a year) by villagers to facilitate agricultural, pastoral and cynegetic\r\nactivities.\r\nThe production of wood will be provided by the plantations of Acacia auriculoformis. The coal transformation\r\nwill be carried out using improved traditional carbonization techniques. The bags of coal produced will then\r\nbe transported to Brazzaville and will mainly supply the local industry.\r\nThe Acacia rows will be intercropped with lines of food crops, forming agroforestry plantations. Food crops will be managed by local communities and will ensure self-sustainability while supplying the local food chain.",
      location: {
        latitude: -3.894407,
        longitude: 15.555597,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "36102",
      total_buffer_pool_credits: 1184,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "7454 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_1332: {
      resourceIdentifier: "1332",
      resourceName:
        "Reforestation Project in Yingjing County, Sichuan Province",
      description:
        "The project is located in Yingjing County, Sichuan Province, China, which is the conjunction zone of Qionglai and Daxiangling Mountain Range. The project is to establish forest on the land previously logged to generate GHG emission reductions and contribute to local sustainable development. The project is jointed implemented by Paocaowan Forestry Farm and Nibashan Forestry Farm. 159.2ha of mingle forest is to be established by direct planting on degraded lands. 3 land areas covering one village of a township and one forest farm in Yingjing County are involved in the project.  The implementation of the project would reduce the GHG emissions for 100,973tCO2e in 30 years, with an average annual GHG emission of 3,365tCO2e. Climate, Community and Biodiversity (CCB) standard has been applied to the project to ensure the integrated benefit of climate, community and biodiversity. The project was registered with CCB standards on March 20 2013.",
      location: {
        latitude: 29.74884,
        longitude: 102.436547,
      },
      vcs_project_status: "On Hold - see notification letter",
      estimated_annual_emission_reduction: "3365",
      total_buffer_pool_credits: 180,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "159 Hectares",
      ccb_project_status: "On Hold - see notification letter",
      sdvista_project_status: null,
    },
    VCS_2365: {
      resourceIdentifier: "2365",
      resourceName:
        "Integrated Project for Reforestation and Agroforestry on Degraded lands in Nicaragua",
      description:
        "The proposed ARR VCS project plans to reforest and rehabilitate a total area of 4,204 hectares until 2030 in Nicaragua. Since 2016, 677 hectares of pure teak (Tectona grandis) and, to a lesser extent, cocoa agroforestry systems (Theobroma cacao) have been realized (incl. 2020). This area was realized in the northeast of Nicaragua, in the Autonomous Region of the North Caribbean Coast (RACCN), specifically in the municipalities of Siuna and to a minor extent in Bonanza and within the limits of the buffer zone of the BOSAWAS Biosphere Reserve (RBB), approximately 315 km from the capital of the country Managua. The realized plantations form the first instances of this grouped project. The project foresees a gradual expansion of planted area starting with 100 to 200 hectares per year, adding new project areas to the project within the same area of the RACCN, Nicaragua. After a final harvest of the teak, the area is replanted – this rotation cycle is to continue endlessly. \r\nThe forestry initiative was born in 2008 Bonanza and was managed by Norteak Madera until 2015. Since middle 2015 MLR took the management control of the Project with a different vision, focused on an agro-forestry project combining teak and cacao crops.\r\nThe total current area of the properties of MLR is 5139.55 ha. Of this area, 2315.71 hectare is included in the actual VCS project (areas 2016-2020). The project plans to expand to a total VCS project area of 4,204 hectares (Ha) until 2030, of which 2,567 hectares are commercial plantations, mainly in the Municipality of Siuna, according to the availability of area, labor and other necessary elements, that allow the expansion of the Project in degraded areas. Furthermore, from 2020 onwards, the project manages assigned protection areas for gradual rehabilitation into natural lands, specifically in those areas that have suffered high levels of degradation.",
      location: {
        latitude: 13.607079,
        longitude: -84.877422,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "29287",
      total_buffer_pool_credits: 19052,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "4204 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_1529: {
      resourceIdentifier: "1529",
      resourceName: "Inner Mongolia Chao’er Improved Forest Management Project",
      description:
        "The Inner Mongolia Chao’er Forest Industry IFM Project (hereafter referred to as “the project”) is located in Hulun Buir City, Inner Mongolia Autonomous Region, P.R.China. It is implemented by Chao’er Forest Industry Co. Ltd of China Inner Mongolia Forest Industry Group (hereafter “Project owner”) to protect the once logging forest. \r\nThe proposed project is implemented in three forest farms under the jurisdiction of the Project owner, namely Dacongshan Forest Farm, Quansheng Forest Farm, and Taerqi Forest Farm. The project has 40,027.50ha commercial forest, whose ages ranging from sapling, middle age to mature forest. Before the implementation of the project, the forest within the project area was designed and planted as commercial forest, and logged annually according to the timber production plan approved by local forestry authority . In order to protect the forest ecosystem, improve the ecological environment, increase carbon sinks, reduce GHG emission reductions and slow down climate change, the project proponent decided to implement this improved forest management project activities from December 2017 to December 2077. And from the Project Start Date, PP has stopped the commercial logging in the project area and only allowed tending and managing. \r\nThis project aims to protect 40,027.50ha commercial forest from logging. The Forest Conservation Project activities will be focused on forest resource supervision and monitoring. In order to supervise and monitor any disturbances that may affect the whole forest, a ranger team has been established to monitor the state of the forest with regard to diseases, illegal logging, hunting, fires etc. This ecosystem will then continue to provide its services to all the communities and entities that depend on it.\r\nThe project is expected to generate approximately 8,372,662 tCO2e with buffer deduction during the 30 years’ crediting period, with the annual emission reductions of 279,089 tCO2e.",
      location: {
        latitude: 47.5,
        longitude: 120.283,
      },
      vcs_project_status: "On Hold - see notification letter",
      estimated_annual_emission_reduction: "90035",
      total_buffer_pool_credits: 151803,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "IFM",
      project_acreage: "11010 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_1960: {
      resourceIdentifier: "1960",
      resourceName: "Northern Great Plains Regenerative Grazing Project",
      description:
        "The Northern Great Plains Regenerative Grazing project aims to remove greenhouse gases from the atmosphere by implementing sustainable grazing management on multiple ranches in Montana. It is a grouped projected starting with 33,237 acres with annual estimates 27,435 VERs annually once practices are fully implemented. Planned grazing will increase the rest and rotation on pastures above baseline practices and reduce unrestricted grazing of livestock. Smaller pastures with more rotations allow the recovery of perennial grasses, which foster greater carbon inputs, higher retention of carbon as lignin and cellulose, and greater belowground production. This results in the sequestration of greenhouses gases from the atmosphere to the soil. \r\nPUBLIC COMMENT PERIOD: This project was open for public comment from 8 October – 7 November 2019. No comments were received during this time.",
      location: {
        latitude: 46.879167,
        longitude: -110.36166,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "32514",
      total_buffer_pool_credits: 9163,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ALM",
      project_acreage: "13451 Acres",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_2551: {
      resourceIdentifier: "2551",
      resourceName: "BRAZILIAN AMAZON APD GROUPED PROJECT",
      description:
        "The Brazilian Amazon APD Grouped Project (GPD) aims the forest conservation on private properties located in the nine states of the Legal Amazon. \r\nThe GPD main goal it is to create positive economic incentives to landowners for the rainforest and Cerrado conservation in private areas, through income generation from carbon credits commercialization.\r\nAccording to national law 12.651, the Brazilian forest code, landowners must conserve 80% of the forest cover and 35% of the Cerrado areas on properties located in the Legal Amazon.\r\nIn this way, the areas with forest cover exceeding this percentage can be legally converted to other land uses for commercial activities such as cattle raising or agricultural projects, with the authorization of the responsible environmental agency in each state.\r\nThe landowners who decide to join the initiative, by giving up their right to legally clear their forest areas will be able to access financial resources from the carbon voluntary market, becoming BRCarbon partners. The partnership between BRCarbon (BRC) and landowners will result in legal protection to forests, forest monitoring by satellite images, forest biomass inventory using drones and innovative aero photogrammetry techniques associated with LIDAR technology, property surveillance, wildfire monitoring, prevention and firefighting activities, threatened species protection and social engagement activities with traditional communities living inside the project area.\r\nBRC will be responsible for the development, implementation, monitoring and certification of the project instances. The landowner’s counterpart is to allow project activities to be implemented in their areas, in addition to freely committing to their long-term conservation.\r\nIn this way, BRC expects to escalate the climate impact promoted by the implementation of carbon projects, bringing positive net benefits to communities and biodiversity.",
      location: {
        latitude: -10.265973,
        longitude: -69.532794,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "812538",
      total_buffer_pool_credits: 494438,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "30751 Hectares",
      ccb_project_status: "Verification approved",
      sdvista_project_status: null,
    },
    VCS_1493: {
      resourceIdentifier: "1493",
      resourceName:
        "Mangrove restoration and coastal greenbelt protection in the East coast of Aceh and North Sumatra Province, Indonesia",
      description:
        "The goal of this project is to increase the environmental carrying capacity of mangrove ecosystems in the east coast of Northern Sumatra for carbon sequestration, natural disaster risk reduction and local livelihood improvement. Ecological improvement, climate change mitigation, economic consideration and local community participation will be the main-stream and the spirit of this proposed project. By helping to ensure that the mangrove and more generally the coastal green-belt are well maintained, the project will support Sumatra’s future ecological, social and economic development. During the first 3-4 years of mangrove restoration, the project will restore more than 5,000 ha of degraded mangrove.  Undergoing validation and verification to the CCB Standards: public comment period – 19 August – 18 September 2019. The following documents are undergoing public comment:    1)  CCB_PROJ_DESC_ENG_DRAFT_1493_31JUL2019    2)  CCB_PROJ_DESC_SUM_BAH_DRAFT_1493_31JUL2019    3)  CCB_MON_REP_ENG_",
      location: {
        latitude: 4.65,
        longitude: 97.59,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "124706",
      total_buffer_pool_credits: 48955,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "1000 Hectares",
      ccb_project_status:
        "Validation and verification public comment period expired",
      sdvista_project_status: null,
    },
    VCS_1367: {
      resourceIdentifier: "1367",
      resourceName: "EFM Improved Forest Management Group Project",
      description:
        "The EFM Improved Forest Management Project is a group project that has been developed using the Verified Carbon Standard (VCS) and the associated VM0003 Methodology for improved forest management through extension of rotation age (IFM ERA) on EFM managed forestlands. The geographic areas that are eligible under this group project are forestlands located within the Pacific Northwest States of Oregon, Washington and California. Another eligibility constraint is that the project areas must be managed according to FSC Standards. The first project activity instance of this project is the Moss Creek Reserve Project Area which is 982 acres and is located within the Moss Creek watershed on the Garibaldi Forest property. The Garibaldi Forest property is 4822 acres of private land owned in fee by Garibaldi Forest Management and managed by EFM Investments & Advisory (EFM). In 2019 EFM added a second and third instance to the project, which increased the project area to 27,328 acres. ~ EFM is a for-profit FSC certified forestland investment manager that manages 130,000+ acres forestland in the Pacific Northwest.",
      location: {
        latitude: 45.551814,
        longitude: -123.830556,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "5001",
      total_buffer_pool_credits: 24685,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "IFM",
      project_acreage: "27328 Acres",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_994: {
      resourceIdentifier: "994",
      resourceName: "TIST Program in India, VCS-001",
      description:
        "Since its inception in 1999, over 63,000 participants organized into over 8,900 TIST Small Groups have planted over ten million trees in Tanzania, India, Kenya, Uganda, Nicaragua, and Honduras - accomplishing GhG sequestration through tree planting, creating a potential long-term income stream, and developing sustainable environments and livelihoods. Currently over 50,000 TIST participants in over 6,900 Small Groups are registered in the TIST program in Kenya and are working to break their local cycle of deforestation, drought and famine.  The trees planted in tens of thousands of discrete groves and land parcels are already beginning to reduce erosion, stabilize and enrich the soil, and will soon be providing shade.    VCS 001:  This is a VCS grouped project, is a subset of the TIST reforestation project in India and applies to 452 Small Groups, 2,599 members, 924 project areas and 671.8 ha.  TIST Progam in India VCS 001 is the same project as TIST Program in India CCB 001.,",
      location: {
        latitude: 12.510175,
        longitude: 79.66785,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "11047",
      total_buffer_pool_credits: 27551,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "2382 Hectares",
      ccb_project_status: "Verification approved",
      sdvista_project_status: null,
    },
    VCS_2532: {
      resourceIdentifier: "2532",
      resourceName: "Cumare carbon project",
      description:
        "The project comprises a total of 10.673 ha of land previously under extensive grazing by beef cattle, on which afforestation for obtaining timber products and for sequestering large amounts of carbon dioxide from the atmosphere are established.\r\nThe project area is located in Colombia. Both properties “El Porvenir” and “Caricare” are located in the center-east of Meta department, within San Martin and Puerto Gaitan municipality. The areas are homogeneous in terms of soil types, climate, land use history and socio-economic conditions.\r\nForests is based on 10-year rotation Eucalyptus pellita, Eucalyptus Urograndis and Eucalyptus urophylla, and 15 to 16 years rotation Pinus caribea plantations. Pinus spp. plantation have been established and will continue being established as a complement to the short-fibre production (Eucalyptus spp.), since the species is best suitable for very low productive soils.\r\nForest project activity is currently in its sixth year after project start-date, and plantation will be completed by year ten of project. Forests will be replanted after clear-cut harvest when the seedling genetic material compensates the cost of soil preparation and plantation. Clone plantations could be managed with regrowth, avoiding the soil preparation costs and its carbon stock reduction. Planted forests will remove carbon dioxide from the atmosphere and store it in different carbon pools (living above-ground and below- ground biomass, soil, litter, non-tree vegetation, dead wood and harvested wood products).\r\nMonitoring will cover carbon stock changes for living above-ground pool. Below ground biomass will be estimated indirectly based on above-ground biomass measurements. Litter, dead wood and soil organic carbon pools will be estimated based on conservative default factors from the methodological tool. Non- tree vegetation and harvested wood products will not be accounted as per the methodology applied. The potential non-permanence of stored carbon will be considere",
      location: {
        latitude: 3.624693,
        longitude: -72.379098,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "29180",
      total_buffer_pool_credits: 50355,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "10673 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_1311: {
      resourceIdentifier: "1311",
      resourceName:
        "Carbon Emissions Reduction Project in the Corridor Ankeniheny-Zahamena (CAZ) Protected Area, Madagascar",
      description:
        "The Ankeniheny-Zahamena Corridor (CAZ) has long been regarded as one of Madagascar’s top conservation priorities and numerous studies have catalogued its rich biodiversity.  To date over 2,043 species of plants have been identified (85% are endemic).The CAZ carbon project covers 370,032 hectares of Madagascar’s eastern humid rainforest and provides important ecosystem services to both the surrounding area and greater region.  It protects the headwaters of eight large rivers that directly supply approximately 325,000 residents with water.By far the greatest threat to the forest corridor in terms of forest loss is slash-and-burn agriculture and this threatens the long term existence of the corridor.  If this pressure is not alleviated, CAZ will soon disappear and with it the incredible biodiversity it houses, but also the essential ecosystem services it provides to countless rural families in the area.In order to reduce deforestation in CAZ, the Government of Madagascar and Conservation International developed the strategy of establishing an avoided deforestation carbon project that would provide direct incentives and alternative livelihood activities for communities living around the forest corridor.",
      location: {
        latitude: -17.76201,
        longitude: 48.846282,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "1011973",
      total_buffer_pool_credits: 23496,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "370032 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_1118: {
      resourceIdentifier: "1118",
      resourceName: "Suruí Forest Carbon Project",
      description:
        "The Suruí Forest Carbon Project (SFCP) aims to halt deforestation and its associated greenhouse gas (GHG) emissions in an area under deforestation pressure in the Sete de Setembro Indigenous Territory (TISS). The project is based on four themes: Forest Protection and Environment, Food Security and Sustainable Production, Institutional Strengthening; Development and implementation of a financial mechanism - Suruí Fund. This set of activities is designed to end deforestation in the TISS by attacking its two main roots: the lack of economic alternatives to ensure the well-being of the Paiter Suruí, and the appearance of external actors to conduct illegal activities. In order to establish the baseline of the project, a projection model of land use change in the TISS was developed. This model is called SimSuruí and is based on system dynamics to represent the existing system in TISS, its agents and their interactions with the surrounding vegetation. The objective of the SFCP is to prevent 13,575.3 hectares of tropical forests from being cleared in the TISS for 30 years (crediting period), to avoid the emission a long term average of 7,423,806.2 tCO2e in the atmosphere and to contribute to the preservation of the Paiter Suruí lifestyle and traditions.",
      location: {
        latitude: -11.009945,
        longitude: -61.151479,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "247460",
      total_buffer_pool_credits: 24183,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "31994 Hectares",
      ccb_project_status: "Validation expired",
      sdvista_project_status: null,
    },
    VCS_1325: {
      resourceIdentifier: "1325",
      resourceName: "Village Climate Solutions",
      description:
        "This project seeks to reduce green house gas emissions caused by unplanned deforestation on 41,924 ha of communal village land, while simultaneously promoting rural economic development and biodiversity conservation in Lindi Rural District in Tanzania. The primary project activities included land-use planning and establishing village forest reserves, which gives village governments secure tenure and regulatory authority over the forests within their boundaries. The project has also supported community members to develop new forest friendly livelihoods like bee-keeping, and improved credit accessibility for community members looking to establish small businesses. Finally, village earnings from the sale of verified GHG emissions reductions and royalties charged for sustainable forest use, will help to offset the opportunity costs of REDD.",
      location: {
        latitude: -9.939811,
        longitude: 39.458677,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "350721",
      total_buffer_pool_credits: 3725,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "327234 Hectares",
      ccb_project_status: "Under validation and verification",
      sdvista_project_status: null,
    },
    VCS_1503: {
      resourceIdentifier: "1503",
      resourceName: "RESEX Rio Preto-Jacundá REDD+ Project",
      description:
        "RESEX Rio Preto-Jacundá REDD+ Project is a partnership between Biofílica and the residents of Resex Rio Preto-Jacundá, represented by the Neighborhood Association of The Extractive Reserve Rio Preto-Jacundá and Ribeirinhos do Rio Machado (ASMOREX), having the Center of Studies Rioterra (CES Rioterra) and the Executive Board of the Extractive Reserves of Anari Valley (CDREX) as partners in the planning and implementation of the activities of the Project. Located in the extractive reserve of the same name at the municipalities of Machadinho D’Oeste and Cujubim, northeastern of the State of Rondônia,  RESEX Rio Preto-Jacundá has a territory of 95 thousand hectares. It was created in 1996 by State Decree 7,336 and has a history of struggle for rubber tappers rights.The main goal of RESEX Rio Preto-Jacundá REDD+ Project is the promotion of the sustainability of the exctractive community by reducing forest degradation and unplanned and illegal deforestation and consequent emission of greenhouse gases (GHG), achieved through a list of activities funded by the sale of carbon credits.",
      location: {
        latitude: -8.863412,
        longitude: -62.288229,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "151801",
      total_buffer_pool_credits: 84327,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "68255 Hectares",
      ccb_project_status: "Verification approval requested ",
      sdvista_project_status: null,
    },
    VCS_1122: {
      resourceIdentifier: "1122",
      resourceName: "April Salumei Rainforest Community Conservation Project",
      description:
        "The April Salumei REDD Project is the pilot project for Papua New Guinea. The aim of the project is to protect the forest and biodiversity of the area (603,579ha) whilst providing an important source of income for the traditional owners. The traditional owners have formed the April Salumei Working Group to assist with the management of the project. 60% of all revenue goes directly to the landowners who actively determine the allocation of funds to activities such health care, education facilities, infrastructure and the development sustainable agricultural activities for the local people whilst preserving the rich cultural traditions and culture.  The project was validated to the Climate, Community & Biodiversity Standards 2nd Ed. at the gold level for exceptional biodiversity benefits (the validation expired 12 June 2016). Appropriately, Papua New Guinea is one of the world’s most biologically diverse regions on the planet, and is home to an estimated 5 – 7% of the world’s total biodiversity.",
      location: {
        latitude: -4.66352,
        longitude: 142.679259,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "1628812",
      total_buffer_pool_credits: 297168,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "IFM; REDD",
      project_acreage: "196703 Hectares",
      ccb_project_status: "Validation expired",
      sdvista_project_status: null,
    },
    VCS_672: {
      resourceIdentifier: "672",
      resourceName:
        "INFAPRO Rehabilitation of logged-over dipterocarp forest in Sabah, Malaysia",
      description:
        "The project rehabilitates 25,000 ha of severely logged-over mixed dipterocarp rainforest in Sabah, Malaysia and prevents relogging of the forest in this area. In the absence of the project activity, the forest would be re-logged and would only slowly recuperate due to the high quantities of vines and climbing bamboos suppressing the remnant trees and the natural regeneration process.",
      location: {
        latitude: 5.027872,
        longitude: 117.803684,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "138013",
      total_buffer_pool_credits: 51020,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "IFM",
      project_acreage: "25000 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_824: {
      resourceIdentifier: "824",
      resourceName: "TIST Program in Uganda, VCS 001",
      description:
        "Since its inception in 1999, over 63,000 participants organized into over 8,900 TIST Small Groups have planted over ten million trees in Tanzania, India, Kenya, and Uganda - accomplishing GhG sequestration through tree planting, creating a potential long-term income stream, and developing sustainable environments and livelihoods. Currently over 5,000 TIST participants in over 800 Small Groups are registered in the TIST program in Uganda and are working to break their local cycle of deforestation, drought and famine.  The trees planted in tens of thousands of discrete groves and land parcels are already beginning to reduce erosion, stabilize and enrich the soil, and will soon be providing shade.  This PD is for a subset of the reforestation project in Uganda and applies to 291 of the Small Groups, 1,662 members, 1,000 project areas and 777.1 ha.  TIST Program in Uganda VCS-001, -002 -003 and -004 comprise the project TIST Program in Uganda CCB-001.  Undergoing verification to the CCB St",
      location: {
        latitude: 0.557316,
        longitude: 30.176894,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "24348",
      total_buffer_pool_credits: 27224,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "777 Hectares",
      ccb_project_status: "Verification approved",
      sdvista_project_status: null,
    },
    VCS_1866: {
      resourceIdentifier: "1866",
      resourceName:
        "XinJiang Makit County Afforestation Carbon Sequestration Project",
      description:
        "XinJiang Makit County Afforestation Carbon Sequestration Project (here after “the project”) is located in Makit County, Xinjiang Uygur Autonomous Region of China, whose aim is to increase carbon sequestration and contribute to local sustainable development by planting trees on the desert lands. The project proponent is Makit Base Junlian Cotton Industry Co., Ltd. 6,697.84 ha of forest is to be planted by direct planting on desert lands in Makit County. There is no natural renewal and reforestation before the project. The implementation of the project would generate GHG emission removals and improve local environment through growing of the trees, enhance the capabilities of local communities and residents by providing their relevant technical skills and training, and increase local biodiversity as a result of establishing a forest of native trees (Populus alba var, Haloxylon ammodendron, Elaeagnus angustifolia Linn).",
      location: {
        latitude: 38.858983,
        longitude: 77.806055,
      },
      vcs_project_status: "On Hold - see notification letter",
      estimated_annual_emission_reduction: "90393",
      total_buffer_pool_credits: 66328,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR; IFM; REDD",
      project_acreage: "6697 Hectares",
      ccb_project_status: "On Hold - see notification letter",
      sdvista_project_status: null,
    },
    VCS_1911: {
      resourceIdentifier: "1911",
      resourceName: "King County Rural Forest Carbon Project",
      description:
        "The King County Rural Forest Carbon Project is a set of dispersed properties located within King County (Figure 1), in western Washington State near the city of Seattle, WA. It is a Grouped Project that includes a combination of properties or title rights acquired and managed by King County, and properties or title rights owned and managed by 3rd Party Landowners. The King County Rural Forest Carbon Project achieves net GHG emissions reductions and removals through the avoidance of emissions due to commercial logging and forest removal for rural residential development expected in the baseline scenario.  PUBLIC COMMENT PERIOD: This project was open for public comment from 28 June – 28 July 2019.",
      location: {
        latitude: 47.47,
        longitude: -121.84,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "9195",
      total_buffer_pool_credits: 9348,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "IFM",
      project_acreage: "1861 Acres",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_1764: {
      resourceIdentifier: "1764",
      resourceName:
        "Reforestation and Restoration of degraded mangrove lands, sustainable livelihoods and community development in Myanmar",
      description:
        "The proposed project falls under the ARR (Afforestation, reforestation, and Revegetation) category of the Verified Carbon Standard (VCS). The project will be implemented on 2265.47 ha of degraded lands of the Northern part of Ayeyarwady Division of Myanmar. The lands that will be restored under the project belong to Magyi, Thabawkan and Thaegone village tracts and this restoration will create a healthy mangrove ecosystem.  The objective of the project is to establish and maintain a sustainably managed mangrove ecosystem for carbon sequestration, natural disaster risk reduction, poverty reduction with sustainable livelihoods in the coastal communities. A vital component of the project is the conservation of bio-diversity and establishment of the first mangrove gene bank in Myanmar.  This project was open for public comment from 12 June - 12 July 2017. Comments that were received are summarized in the public comment summary (OTHER_1694_11JUL2017)..",
      location: {
        latitude: 17.067264,
        longitude: 94.465384,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "184006",
      total_buffer_pool_credits: 48937,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR; WRC",
      project_acreage: "2060 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
    VCS_2502: {
      resourceIdentifier: "2502",
      resourceName: "TAHUAMANU AMAZON REDD PROJECT",
      description:
        "The proposed project is based on the enhancement and strengthening of the sustainable forest management of a consolidated group of forest concessions managed by a local company with long forest tradition, MADERACRE SAC, who also has previous successful experience with REDD+.\r\nThe whole area managed by MADERACRE SAC, including the current proposed project area and others already VCS/CCB verified, are FSC certified, which guarantees that logging activities are being done under adequate techniques.\r\nThe area faces increasing threats from unsustainable agrarian practices from neighbouring local religious communities and others.\r\nTo deal with it, the project plans to combine an increase in protection measures (patrolling, working together with other forest concessions and the forest and political authorities) with the promotion of productive activities for neighbouring communities, as a strategy to offer alternative sources of income that do not imply the clearing of forest areas. Based on this approach, the project expects to reduce projected deforestation.\r\nThe project is located in Madre de Dios, a region in the south-east of the Peruvian Amazon with the most accelerated deforestation rate of Peru.",
      location: {
        latitude: -11.359047,
        longitude: -69.973701,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "1575108",
      total_buffer_pool_credits: 416297,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "171584 Hectares",
      ccb_project_status: "Verification approval requested ",
      sdvista_project_status: null,
    },
    VCS_1382: {
      resourceIdentifier: "1382",
      resourceName:
        "The Envira Amazonia Project - A Tropical Forest Conservation Project in Acre, Brazil",
      description:
        "The Envira Amazonia Project is a VCS and CCBS designed REDD+ project in the State of Acre, Brazil which aims to protect up to 200,000 hectares of tropical rainforest. Furthermore, the Envira Amazonia Project will simultaneously preserve rich biodiversity and a wide range of ecosystem services, provide direct benefits to local communities, and mitigate the release of ~12.6 million metric tonnes of carbon dioxide emissions over the first 10 years of the Project.",
      location: {
        latitude: -8.847445,
        longitude: -70.177176,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "1259646",
      total_buffer_pool_credits: 4503981,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "39301 Hectares",
      ccb_project_status: "Verification approval requested ",
      sdvista_project_status: null,
    },
    VCS_1899: {
      resourceIdentifier: "1899",
      resourceName: "Sumatra Merang Peatland Project (SMPP)",
      description:
        "The SMPP aims to restore the ecological functions of the Merang peatland through the use of sustainable land-use models that benefit critically endangered biodiversity and provide benefits for local communities. These overarching objectives will be achieved by implementing ecosystem and habitat restoration activities while establishing sustainable avenues for economic success amongst the local communities.",
      location: {
        latitude: -2.019124,
        longitude: 104.1383,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "1338569",
      total_buffer_pool_credits: 439310,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR; WRC",
      project_acreage: "22922 Hectares",
      ccb_project_status: "Under Verification",
      sdvista_project_status: null,
    },
    VCS_953: {
      resourceIdentifier: "953",
      resourceName:
        "The Paraguay Forest Conservation Project - Reduction of GHG emissions from deforestation and forest degradation in the Chaco-Pantanal ecosystem",
      description:
        "The project consists of the purchase and protection of 4,745 ha of forested land with High Conservation Values in the eastern Chaco-Pantanal transition zone in Alto Paraguay, threatened in the absence of the project with transformation into cattle ranching. The project goal is to conserve the natural and cultural values of the area, including its sequestered carbon. Climate benefits are achieved by preventing deforestation.Ownership and management of the area is shared between a Paraguayan biodiversity conservation NGO (Guyra Paraguay) and the Yshir indigenous community (represented by the Unión de Comunidades de la Nación Yshir or UCINY), with legal safeguards to ensure permanence of conservation management regime. The project is also submitted for CCBA validation.This is an initial project instance of a grouped project. Other instances are envisaged, replicating the same pattern.PUBLIC COMMENT PERIOD:This project was open for public comment from 01 November - 01 December 2019. 1)CCB_MONIT_REP_SUM_ESP_DRAFT_953_25FEB2013_24FEB20182)CCB_MONIT_REP_ENG_DRAFT_953_25FEB2013_24FEB2018",
      location: {
        latitude: -20.967034,
        longitude: -58.976599,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "12784",
      total_buffer_pool_credits: 12417,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "4745 Hectares",
      ccb_project_status: "Verification approved",
      sdvista_project_status: null,
    },
    VCS_1215: {
      resourceIdentifier: "1215",
      resourceName: "The Makira Forest Protected Area in Madagascar",
      description:
        "Through carbon credit sales from avoided deforestation, the Makira Forest Protected Area REDD+ Project will finance the long-term conservation of one of Madagascar’s most pristine remaining rainforest systems containing rare and threatened biodiversity, improve community land stewardship and governance, and support sustainable livelihood practices for local people. In 2001, the Government of Madagascar, in collaboration with the Wildlife Conservation Society (WCS), created the 372,470-hectare Makira Forest Protected Area. In 2012, the Makira Forest became Makira Natural Park: Madagascar’s newest and largest park, and an IUCN category II protected area. The Makira Forest Protected Area Project will prevent more than 33 million tonnes of CO2 emissions over the course of 30 years.",
      location: {
        latitude: -15.179273,
        longitude: 49.538719,
      },
      vcs_project_status: "Late to verify",
      estimated_annual_emission_reduction: "1267231",
      total_buffer_pool_credits: 127671,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "REDD",
      project_acreage: "360060 Hectares",
      ccb_project_status: "Verification expired",
      sdvista_project_status: null,
    },
    VCS_2412: {
      resourceIdentifier: "2412",
      resourceName:
        "Mindanao Tree Planting Program for our Climate and Communities (MinTrees)",
      description:
        "The Mindanao Tree Planting Program for our Climate and Communities (MinTrees) is a de-centralized, long-term rural sustainable development project focused on smallholder agriculture and forest management. It reaches a large number of beneficiary households and municipalities in the Mindanao region of the Philippines. It involves activities of Afforestation, Reforestation and Revegetation (ARR), especially agroforestry systems and ecological reforestation.\r\nMinTrees is scaling up according to a long-term roll-out strategy with several instances of project activities in specific areas. Therefore, it is a Grouped Project that defines large parts of the Mindanao region as geographically defined area for the grouped project instances. For example, annual planting waves keep expanding the project area of ARR instances with agroforestry and reforestation activities. Each project instance has and will have its unique specified geographic project area and where applicable reference regions, leakage management areas etc.\r\n\r\nThe project’s community objectives are the inclusion and sustainable livelihood development for tens of thousands of rural community households from both indigenous and non-indigenous origins. The project is applying a unique approach to blending or combining several finance streams for rural transformation including sustainable agri-business, soft loan agri-lending, development grants and climate finance. For productive lands of the ARR component, rural communities are assisted with the capacity building and empowerment of their farming groups, cooperatives and clusters. They receive access to a complete and successfully tested package of diversified agroforestry production, training, soft loan for working capital, quality control, extension services and most importantly a clear and specific market access.",
      location: {
        latitude: 7.272844,
        longitude: 126.221372,
      },
      vcs_project_status: "Verification approval requested",
      estimated_annual_emission_reduction: "33015",
      total_buffer_pool_credits: 1410,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "30000 Hectares",
      ccb_project_status: "Under Verification",
      sdvista_project_status: null,
    },
    VCS_961: {
      resourceIdentifier: "961",
      resourceName:
        "‘El Arriero ’ Afforestation on degraded grasslands under extensive grazing project",
      description:
        "The project comprises a total of 5,377 ha of land previously under extensive grazing by beef cattle, on which Afforestation for obtaining high-value, long-lived timber products and for sequestering large amounts of carbon dioxide from the atmosphere will be established.",
      location: {
        latitude: -32.789946,
        longitude: -55.23134,
      },
      vcs_project_status: "Registered",
      estimated_annual_emission_reduction: "18271",
      total_buffer_pool_credits: 193841,
      primary_project_category: "Agriculture Forestry and Other Land Use",
      subcategory: "ARR",
      project_acreage: "5377 Hectares",
      ccb_project_status: null,
      sdvista_project_status: null,
    },
  },
];
  
  
 