export const COUNTRY_MAP: Record<string, string> = {
  AFG: 'Afghanistan',
  ALB: 'Albania',
  DZA: 'Algeria',
  AND: 'Andorra',
  AGO: 'Angola',
  ARG: 'Argentina',
  ARM: 'Armenia',
  AUS: 'Australia',
  AUT: 'Austria',
  AZE: 'Azerbaijan',

  BHS: 'Bahamas',
  BHR: 'Bahrain',
  BGD: 'Bangladesh',
  BRB: 'Barbados',
  BLR: 'Belarus',
  BEL: 'Belgium',
  BLZ: 'Belize',
  BEN: 'Benin',
  BTN: 'Bhutan',
  BOL: 'Bolivia',
  BIH: 'Bosnia and Herzegovina',
  BWA: 'Botswana',
  BRA: 'Brazil',
  BRN: 'Brunei',
  BGR: 'Bulgaria',

  KHM: 'Cambodia',
  CMR: 'Cameroon',
  CAN: 'Canada',
  CPV: 'Cape Verde',
  CAF: 'Central African Republic',
  TCD: 'Chad',
  CHL: 'Chile',
  CHN: 'China',
  COL: 'Colombia',
  COM: 'Comoros',
  CRI: 'Costa Rica',
  HRV: 'Croatia',
  CUB: 'Cuba',
  CYP: 'Cyprus',
  CZE: 'Czech Republic',

  DNK: 'Denmark',
  DJI: 'Djibouti',
  DOM: 'Dominican Republic',

  ECU: 'Ecuador',
  EGY: 'Egypt',
  SLV: 'El Salvador',
  EST: 'Estonia',
  ETH: 'Ethiopia',

  FIN: 'Finland',
  FRA: 'France',

  GEO: 'Georgia',
  DEU: 'Germany',
  GHA: 'Ghana',
  GRC: 'Greece',
  GTM: 'Guatemala',

  HTI: 'Haiti',
  HND: 'Honduras',
  HUN: 'Hungary',

  ISL: 'Iceland',
  IND: 'India',
  IDN: 'Indonesia',
  IRN: 'Iran',
  IRQ: 'Iraq',
  IRL: 'Ireland',
  ISR: 'Israel',
  ITA: 'Italy',

  JAM: 'Jamaica',
  JPN: 'Japan',
  JOR: 'Jordan',

  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  KWT: 'Kuwait',
  KGZ: 'Kyrgyzstan',

  LAO: 'Laos',
  LVA: 'Latvia',
  LBN: 'Lebanon',
  LKA: 'Sri Lanka',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',

  MYS: 'Malaysia',
  MDV: 'Maldives',
  MLT: 'Malta',
  MEX: 'Mexico',
  MNG: 'Mongolia',
  MAR: 'Morocco',
  MOZ: 'Mozambique',

  NPL: 'Nepal',
  NLD: 'Netherlands',
  NZL: 'New Zealand',
  NGA: 'Nigeria',
  NOR: 'Norway',

  OMN: 'Oman',

  PAK: 'Pakistan',
  PAN: 'Panama',
  PER: 'Peru',
  PHL: 'Philippines',
  POL: 'Poland',
  PRT: 'Portugal',

  QAT: 'Qatar',

  ROU: 'Romania',
  RUS: 'Russia',
  RWA: 'Rwanda',

  SAU: 'Saudi Arabia',
  SEN: 'Senegal',
  SGP: 'Singapore',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  ZAF: 'South Africa',
  KOR: 'South Korea',
  ESP: 'Spain',
  SWE: 'Sweden',
  CHE: 'Switzerland',

  THA: 'Thailand',
  TUN: 'Tunisia',
  TUR: 'Turkey',

  UKR: 'Ukraine',
  ARE: 'United Arab Emirates',
  GBR: 'United Kingdom',
  USA: 'United States',

  VNM: 'Vietnam',

  ZMB: 'Zambia',
  ZWE: 'Zimbabwe',
};
